/**
 * tests/test_golden.js — Regression golden test for Cα Langevin (4W52 10 steps, seed 42).
 *
 * Loads tests/golden/4w52_10steps.json generated by tests/generate_golden.js,
 * rebuilds the same 10-step trajectory deterministically via SeededRNG seed=42
 * (patched Math.random), and asserts posHash/energy match.
 *
 * Runnable: node tests/test_golden.js
 * Prints PASS or FAIL per spec tolerance 1e-9.
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

import { SeededRNG } from "../src/seeded-rng.js";
import { parseCa, selectSystem } from "../src/pdb.js";
import { ForceField } from "../src/forcefield.js";
import { LangevinIntegrator } from "../src/integrator.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function findPdb() {
  const candidates = [
    path.resolve(process.cwd(), "4w52.pdb"),
    path.resolve(__dirname, "..", "4w52.pdb"),
    path.resolve(__dirname, "4w52.pdb"),
  ];
  for (const p of candidates) if (fs.existsSync(p)) return p;
  throw new Error(`4w52.pdb not found (tried ${candidates.join(", ")})`);
}

function findGolden() {
  const candidates = [
    path.resolve(process.cwd(), "tests/golden/4w52_10steps.json"),
    path.resolve(__dirname, "golden/4w52_10steps.json"),
    path.resolve(__dirname, "..", "tests/golden/4w52_10steps.json"),
  ];
  for (const p of candidates) if (fs.existsSync(p)) return p;
  throw new Error(`golden file not found (tried ${candidates.join(", ")})`);
}

function arrayHash(arr, scale = 1000) {
  let h = 0x811c9dc5;
  for (let i = 0; i < arr.length; i++) {
    const q = Math.round(arr[i] * scale);
    h ^= (q & 0xff);
    h = Math.imul(h, 0x01000193);
    h ^= ((q >> 8) & 0xff);
    h = Math.imul(h, 0x01000193);
    h ^= ((q >> 16) & 0xff);
    h = Math.imul(h, 0x01000193);
  }
  return (h >>> 0).toString(16).padStart(8, "0");
}

async function main() {
  const pdbPath = findPdb();
  const goldenPath = findGolden();
  const golden = JSON.parse(fs.readFileSync(goldenPath, "utf-8"));
  const pdbText = fs.readFileSync(pdbPath, "utf-8");

  const seed = golden.seed ?? 42;
  const steps = golden.steps ?? 10;
  const tol = 1e-9;

  const rng = new SeededRNG(seed);
  rng.install();
  let energy, posHash, velHash, pos, vel, dt, timePs;
  try {
    const parsed = parseCa(pdbText);
    const sel = selectSystem(parsed);
    const ff = new ForceField(sel, { rc: 10, gamma: 1.0 });
    const integrator = new LangevinIntegrator(ff.ref, ff, 110);
    integrator.setTemperature(300);
    integrator.setFriction(5.0);

    for (let s = 0; s < steps; s++) integrator.step();

    pos = integrator.pos;
    vel = integrator.vel;
    energy = ff.energy;
    posHash = arrayHash(pos, 1000);
    velHash = arrayHash(vel, 1000);
    dt = integrator.dt;
    timePs = integrator.time;
  } finally {
    rng.restore();
  }

  console.log(`Golden:  energy=${golden.energy} posHash=${golden.posHash} velHash=${golden.velHash} steps=${golden.steps} dt=${golden.dtPs}`);
  console.log(`Current: energy=${energy} posHash=${posHash} velHash=${velHash} steps=${steps} dt=${dt} timePs=${timePs}`);

  const energyDiff = Math.abs(energy - golden.energy);
  const posHashMatch = posHash === golden.posHash;
  const velHashMatch = velHash === golden.velHash;

  // Also compare full pos array if present (rounded to 4 decimals in golden)
  let maxPosDiff = 0;
  if (Array.isArray(golden.pos) && golden.pos.length === pos.length) {
    for (let i = 0; i < pos.length; i++) {
      const d = Math.abs(pos[i] - golden.pos[i]);
      if (d > maxPosDiff) maxPosDiff = d;
    }
    console.log(`max |pos - golden.pos| = ${maxPosDiff} (golden.pos is 4-decimal rounded; expect < 6e-5)`);
  }

  console.log(`energy diff = ${energyDiff} tol=${tol} -> ${energyDiff < tol ? "PASS" : "FAIL"}`);
  console.log(`posHash ${posHashMatch ? "MATCH" : "MISMATCH"} (${posHash} vs ${golden.posHash})`);
  console.log(`velHash ${velHashMatch ? "MATCH" : "MISMATCH"} (${velHash} vs ${golden.velHash})`);

  let ok = true;
  if (energyDiff >= tol && energyDiff >= 1e-9) {
    console.error(`FAIL: energy mismatch ${energy} vs ${golden.energy} diff=${energyDiff} >= ${tol}`);
    ok = false;
  }
  if (!posHashMatch) {
    console.error(`FAIL: posHash mismatch current ${posHash} vs golden ${golden.posHash}`);
    ok = false;
  }
  // velHash check is secondary but still recorded
  if (!velHashMatch) {
    console.warn(`WARN: velHash mismatch (non-fatal if posHash passes) current ${velHash} vs golden ${golden.velHash}`);
    // not fatal for PASS per spec: spec requires posHash/energy, but we enforce posHash strictly
    ok = false;
  }

  if (ok) {
    console.log("PASS: golden regression 4w52_10steps matched");
  } else {
    console.error("FAIL: golden regression mismatch");
    process.exit(1);
  }
}

main().catch((e) => { console.error(e); process.exit(1); });
