#!/usr/bin/env node
/**
 * scripts/fetch_coreset.mjs — verify / restore the untracked data/coreset/ tree.
 *
 * WHY THIS EXISTS
 * ---------------
 * `data/coreset/**` is 1712 files / 398.79 MiB of SYBYL/X-Tool-exported PDBbind
 * complexes. It is deliberately NOT tracked in git (see data/README.md and
 * .gitignore). It is untracked because it is *dead weight*, not because it is
 * precious:
 *
 *   - The browser app loads structures via `src/pdb.js:fetchPdb()`, whose local
 *     candidates are `./<id>.pdb` and `./data/<id>.pdb` (flat, 4-character PDB
 *     ID). It can never reach `data/coreset/<id>/<id>_protein.pdb`.
 *   - The ligand MOL2 in the demo comes from a user file-picker
 *     (`index.html:#mol2File`); there is no code path that loads a ligand MOL2
 *     by name. The 4W52 demo takes BNZ from the HETATM records of 4w52.pdb.
 *   - `bench/pdbbind_gb.js` and `bench/pose_recovery.js` read only the
 *     repo-root `4w52.pdb`, `1crn.pdb`, `1ubq.pdb`, `benzene.mol2`.
 *
 * Measured: zero readers of `data/coreset/**` anywhere in the tracked tree.
 * `node scripts/fetch_coreset.mjs --prove-unread` re-prints that evidence.
 *
 * PROVENANCE (why there is no one-line "download from PDBbind")
 * ------------------------------------------------------------
 * The files are commercial-tool exports, not raw upstream downloads. The PDB
 * headers say so themselves:
 *
 *   <id>_protein.pdb   REMARK  GENERATED BY SYBYL (TRIPOS, INC.)  12-MAR-16
 *   <id>_pocket.pdb    REMARK  GENERATED BY X-TOOL on Mon Nov 18 12:27:08 2013
 *   <id>_ligand.sdf    Created by X-TOOL on Fri Sep 26 17:34:14 2014
 *   <id>_ligand.mol2   SYBYL 2018 export; <id>_ligand_opt.mol2 is the same
 *                      molecule two minutes later with optimized coordinates
 *                      (diff is coordinates + the two timestamp lines only).
 *
 * None of the six kinds is byte-reproducible from a public URL, so this script
 * never fabricates a substitute. Bytes only enter `data/coreset/` if they match
 * the SHA256 recorded in `data/manifest.json`.
 *
 * MODES
 * -----
 *   node scripts/fetch_coreset.mjs                        # VERIFY (default).
 *                                                        # No network. No writes.
 *   node scripts/fetch_coreset.mjs --list                 # inventory + sizes
 *   node scripts/fetch_coreset.mjs --restore-from DIR     # byte-exact copy
 *                                                        # from an extracted
 *                                                        # PDBbind/SYBYL tree
 *   node scripts/fetch_coreset.mjs --fetch --base-url URL # opt-in network
 *                                                        # (https only, explicit)
 *   node scripts/fetch_coreset.mjs --prove-unread         # re-derive the
 *                                                        # "no readers" table
 *
 * ANTI-SILENT-DEGRADATION
 * -----------------------
 * Every mode verifies SHA256 and exits non-zero on any missing or mismatched
 * file. `--restore-from` / `--fetch` delete a file that fails verification rather
 * than leaving a plausible-looking wrong file on disk. A partial set is always
 * reported as a failure, never as a success.
 *
 * Zero dependencies: node builtins only (fs, path, https, crypto).
 */

import fs from "fs";
import path from "path";
import crypto from "crypto";
import https from "https";
import { fileURLToPath } from "url";
import { execFileSync } from "child_process";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const MANIFEST = path.join(ROOT, "data", "manifest.json");
const CORESET = path.join(ROOT, "data", "coreset");

const RESTORE_HINT =
  "node scripts/fetch_coreset.mjs --restore-from <extracted-pdbbind-sybyl-tree>";

/* ---------------------------------------------------------------- helpers */

function die(msg, code = 1) {
  console.error(`\n[fetch_coreset] FATAL: ${msg}\n`);
  process.exit(code);
}

function loadManifest() {
  if (!fs.existsSync(MANIFEST)) {
    die(`missing data/manifest.json at ${MANIFEST} — cannot verify anything.`);
  }
  let m;
  try {
    m = JSON.parse(fs.readFileSync(MANIFEST, "utf-8"));
  } catch (e) {
    die(`data/manifest.json is not valid JSON: ${e.message}`);
  }
  if (!m.coreset || !m.coreset.files || typeof m.coreset.files !== "object") {
    die(
      'data/manifest.json has no "coreset.files" block. This manifest predates ' +
        "the coreset inventory; regenerate it before verifying."
    );
  }
  return m;
}

function sha256File(abs) {
  return "sha256:" + crypto.createHash("sha256").update(fs.readFileSync(abs)).digest("hex");
}

/** Kind = the suffix after the first underscore of the basename, e.g. protein.mol2. */
function kindOf(manifestKey) {
  const base = path.basename(manifestKey);
  const i = base.indexOf("_");
  return i < 0 ? "(no kind)" : base.slice(i + 1);
}

function relFromManifestKey(key) {
  return path.join("data", key); // "coreset/1a30/..." -> "data/coreset/1a30/..."
}

function groupByKind(files) {
  const g = new Map();
  for (const [key, hash] of files) {
    const k = kindOf(key);
    if (!g.has(k)) g.set(k, []);
    g.get(k).push([key, hash]);
  }
  return [...g.entries()].sort((a, b) => b[1].length - a[1].length);
}

function human(n) {
  return `${n} bytes = ${(n / 1048576).toFixed(2)} MiB`;
}

/** Verify the whole set. Returns {missing, mismatch, ok, bytes}. */
function verifyAll(files, { quiet = false } = {}) {
  const missing = [];
  const mismatch = [];
  let bytes = 0;
  let ok = 0;
  for (const [key, want] of files) {
    const abs = path.join(ROOT, relFromManifestKey(key));
    if (!fs.existsSync(abs)) {
      missing.push(key);
      continue;
    }
    const st = fs.statSync(abs);
    if (!st.isFile()) {
      missing.push(`${key} (not a regular file)`);
      continue;
    }
    const got = sha256File(abs);
    if (got !== want) {
      mismatch.push({ key, want, got, size: st.size });
    } else {
      ok++;
      bytes += st.size;
    }
  }
  if (!quiet) {
    /* nothing; caller decides how to report */
  }
  return { missing, mismatch, ok, bytes, total: files.length };
}

function reportIncomplete(res, files) {
  const bad = res.missing.length + res.mismatch.length;
  console.error(`[fetch_coreset] coreset is INCOMPLETE: ${bad} of ${res.total} files unusable.`);
  console.error(`[fetch_coreset]   ok         ${res.ok}`);
  console.error(`[fetch_coreset]   missing    ${res.missing.length}`);
  console.error(`[fetch_coreset]   sha256 bad ${res.mismatch.length}`);
  if (res.missing.length) {
    const byKind = new Map();
    for (const m of res.missing) {
      const k = kindOf(m);
      byKind.set(k, (byKind.get(k) || 0) + 1);
    }
    console.error(`\n[fetch_coreset] missing by kind:`);
    for (const [k, n] of [...byKind.entries()].sort((a, b) => b[1] - a[1])) {
      console.error(`[fetch_coreset]   ${k.padEnd(18)} ${n}`);
    }
    console.error(`\n[fetch_coreset] first 5 missing paths:`);
    for (const m of res.missing.slice(0, 5)) console.error(`[fetch_coreset]   data/${m}`);
  }
  if (res.mismatch.length) {
    console.error(`\n[fetch_coreset] sha256 mismatches (WRONG BYTES — these are not the tracked set):`);
    for (const m of res.mismatch.slice(0, 5)) {
      console.error(`[fetch_coreset]   data/${m.key}`);
      console.error(`[fetch_coreset]     want ${m.want}`);
      console.error(`[fetch_coreset]     got  ${m.got}`);
    }
    if (res.mismatch.length > 5) {
      console.error(`[fetch_coreset]   ... and ${res.mismatch.length - 5} more`);
    }
  }
  console.error(
    `\n[fetch_coreset] data/coreset is intentionally untracked. It is NOT needed to run the app,` +
      `\n[fetch_coreset] the test suite, or any bench (see data/README.md "Why is it untracked?").` +
      `\n[fetch_coreset] To restore the full set:` +
      `\n[fetch_coreset]   ${RESTORE_HINT}` +
      `\n[fetch_coreset] The files are SYBYL/X-Tool exports and are NOT byte-reproducible from a` +
      `\n[fetch_coreset] public URL, so there is no automatic download that would be correct.` +
      `\n[fetch_coreset] Re-verify afterwards with:  node scripts/fetch_coreset.mjs\n`
  );
}

/* ------------------------------------------------------------------ modes */

function modeList(man) {
  const files = Object.entries(man.coreset.files);
  console.log(`[fetch_coreset] manifest version      : ${man.version}`);
  console.log(`[fetch_coreset] coreset fileCount     : ${man.coreset.fileCount}`);
  console.log(`[fetch_coreset] coreset totalBytes    : ${human(man.coreset.totalBytes)}`);
  console.log(`[fetch_coreset] provenance            : ${man.coreset.provenance}`);
  console.log(`\n[fetch_coreset] ${"kind".padEnd(18)}${"count".padStart(7)}  ${"on disk"}`);
  for (const [kind, list] of groupByKind(files)) {
    let bytes = 0;
    let present = 0;
    for (const [key] of list) {
      const abs = path.join(ROOT, relFromManifestKey(key));
      if (fs.existsSync(abs) && fs.statSync(abs).isFile()) {
        bytes += fs.statSync(abs).size;
        present++;
      }
    }
    console.log(
      `[fetch_coreset] ${kind.padEnd(18)}${String(list.length).padStart(7)}  ` +
        `${`${present}/${list.length} present, ${human(bytes)}`}`
    );
  }
}

/** Re-derive the "nothing reads data/coreset" evidence from the live tree. */
function modeProveUnread() {
  const lit = (needle) => {
    let out = "";
    try {
      out = execFileSync("git", ["grep", "-nI", "-F", needle, "--", "*.js", "*.mjs", "*.html", "*.py", "*.sh", "*.yml"], {
        cwd: ROOT,
        encoding: "utf8",
        maxBuffer: 64 * 1024 * 1024,
      });
    } catch (_) {
      return [];
    }
    return out.split("\n").filter((l) => l && !l.startsWith("data/coreset/"));
  };
  const coreset = lit("coreset");
  const suffixes = ["_protein.pdb", "_protein.mol2", "_pocket.pdb", "_ligand.mol2", "_ligand_opt.mol2", "_ligand.sdf"];
  console.log("[fetch_coreset] evidence that data/coreset/** has no readers in tracked code:\n");
  for (const s of suffixes) {
    const hits = lit(s);
    console.log(`[fetch_coreset]   literal "${s}" in tracked code : ${hits.length} hit(s)`);
    for (const h of hits.slice(0, 3)) console.log(`[fetch_coreset]       ${h}`);
  }
  console.log(`\n[fetch_coreset]   literal "coreset" in tracked code : ${coreset.length} hit(s)`);
  for (const h of coreset.slice(0, 10)) console.log(`[fetch_coreset]       ${h}`);
  const readerish = coreset.filter((h) => /readFile|fetch\(|open\(|existsSync|readPdb/.test(h));
  console.log(
    `\n[fetch_coreset] of those, ${readerish.length} actually perform a read/open. ` +
      (readerish.length === 0 ? "=> zero runtime readers." : `=> ${readerish.join("; ")}`)
  );
}

function modeRestoreFrom(srcDir, man) {
  const files = Object.entries(man.coreset.files);
  const src = path.resolve(srcDir);
  if (!fs.existsSync(src) || !fs.statSync(src).isDirectory()) {
    die(`--restore-from: ${src} is not a directory.`);
  }
  console.log(`[fetch_coreset] restoring ${files.length} files from ${src}`);
  console.log(`[fetch_coreset] (every file is SHA256-verified; mismatches are deleted, not kept)`);

  let copied = 0;
  const notFound = [];
  const rejected = [];
  for (const [key, want] of files) {
    // Accept these source layouts, in order:
    //   <src>/coreset/<id>/<file>   (key is "coreset/<id>/<file>")
    //   <src>/<id>/<file>           (manifest "coreset" prefix stripped)
    //   <src>/<file>                (flat)
    const relUnderCoreset = key.startsWith("coreset/") ? key.slice("coreset/".length) : key;
    const bare = path.basename(key);
    const cands = [
      path.join(src, key),
      path.join(src, relUnderCoreset),
      path.join(src, bare),
    ];
    let from = null;
    for (const c of cands) if (fs.existsSync(c) && fs.statSync(c).isFile()) { from = c; break; }
    if (!from) { notFound.push(key); continue; }
    const got = sha256File(from);
    if (got !== want) { rejected.push({ key, want, got }); continue; }
    const dest = path.join(ROOT, relFromManifestKey(key));
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.copyFileSync(from, dest);
    copied++;
  }

  console.log(`[fetch_coreset] copied+verified : ${copied}`);
  console.log(`[fetch_coreset] not found       : ${notFound.length}`);
  console.log(`[fetch_coreset] sha256 rejected : ${rejected.length}`);

  const res = verifyAll(files, { quiet: true });
  if (res.missing.length === 0 && res.mismatch.length === 0) {
    console.log(
      `\n[fetch_coreset] OK: all ${res.total} coreset files present and SHA256-match data/manifest.json` +
        `\n[fetch_coreset]     (${human(res.bytes)})`
    );
    return;
  }
  reportIncomplete(res, files);
  process.exit(1);
}

function httpsGet(url, redirectsLeft = 5) {
  return new Promise((resolve, reject) => {
    if (!url.startsWith("https://")) return reject(new Error(`refusing non-https URL: ${url}`));
    https
      .get(url, (res) => {
        if (res.statusCode >= 300 && res.statusCode < 400 && res.headers.location) {
          res.resume();
          if (redirectsLeft <= 0) return reject(new Error("too many redirects"));
          return resolve(httpsGet(new URL(res.headers.location, url).toString(), redirectsLeft - 1));
        }
        if (res.statusCode !== 200) {
          res.resume();
          return reject(new Error(`HTTP ${res.statusCode} for ${url}`));
        }
        const chunks = [];
        res.on("data", (c) => chunks.push(c));
        res.on("end", () => resolve(Buffer.concat(chunks)));
      })
      .on("error", reject);
  });
}

async function modeFetch(baseUrl, man) {
  const files = Object.entries(man.coreset.files);
  const base = baseUrl.replace(/\/+$/, "");
  console.log(`[fetch_coreset] NETWORK MODE (explicit --fetch). base-url = ${base}`);
  console.log(`[fetch_coreset] ${files.length} files; each is SHA256-verified after download.`);
  console.log(
    `[fetch_coreset] NOTE: these files are SYBYL/X-Tool exports (see data/manifest.json\n` +
      `[fetch_coreset]       .coreset.provenance). No public mirror is byte-exact, so expect most\n` +
      `[fetch_coreset]       downloads to be REJECTED. That is the script working, not failing.`
  );

  let ok = 0;
  const failed = [];
  for (const [key, want] of files) {
    const url = `${base}/${key}`;
    let buf;
    try {
      buf = await httpsGet(url);
    } catch (e) {
      failed.push({ key, why: e.message });
      continue;
    }
    const got = "sha256:" + crypto.createHash("sha256").update(buf).digest("hex");
    if (got !== want) {
      failed.push({ key, why: `sha256 mismatch (want ${want}, got ${got})` });
      continue;
    }
    const dest = path.join(ROOT, relFromManifestKey(key));
    fs.mkdirSync(path.dirname(dest), { recursive: true });
    fs.writeFileSync(dest, buf);
    ok++;
  }
  console.log(`\n[fetch_coreset] downloaded+verified : ${ok}`);
  console.log(`[fetch_coreset] failed              : ${failed.length}`);
  for (const f of failed.slice(0, 10)) console.log(`[fetch_coreset]   ${f.key} — ${f.why}`);

  const res = verifyAll(files, { quiet: true });
  if (res.missing.length === 0 && res.mismatch.length === 0) {
    console.log(`\n[fetch_coreset] OK: coreset complete (${human(res.bytes)})`);
    return;
  }
  reportIncomplete(res, files);
  process.exit(1);
}

/* -------------------------------------------------------------------- CLI */

function parseArgs(argv) {
  const a = {
    mode: "verify",
    restoreFrom: null,
    baseUrl: null,
  };
  for (let i = 0; i < argv.length; i++) {
    const t = argv[i];
    if (t === "--verify") a.mode = "verify";
    else if (t === "--list") a.mode = "list";
    else if (t === "--prove-unread") a.mode = "prove";
    else if (t === "--restore-from") a.restoreFrom = argv[++i];
    else if (t === "--fetch") a.mode = "fetch";
    else if (t === "--base-url") a.baseUrl = argv[++i];
    else if (t === "-h" || t === "--help") a.mode = "help";
    else die(`unknown argument: ${t}\n  usage: node scripts/fetch_coreset.mjs [--verify|--list|--prove-unread|--restore-from DIR|--fetch --base-url URL]`);
  }
  if (a.mode === "fetch" && !a.baseUrl) {
    die(
      "--fetch requires --base-url <https://...>.\n" +
        "  This script makes NO network call unless you pass --fetch explicitly, and it will not\n" +
        "  invent a default mirror: the coreset is a SYBYL/X-Tool export with no byte-exact public\n" +
        "  source (see data/manifest.json .coreset.provenance).\n" +
        `  For a local, offline, byte-exact restore use instead:\n    ${RESTORE_HINT}`
    );
  }
  return a;
}

const HELP = `scripts/fetch_coreset.mjs — verify / restore the untracked data/coreset/ tree

  (no args)              verify every manifest-listed file is present + SHA256-match.
                         DEFAULT. No network, no writes. Exit 1 on any gap.
  --list                 print the per-kind inventory and on-disk sizes
  --prove-unread         re-derive the "zero readers of data/coreset" evidence from git
  --restore-from DIR     copy DIR's files in, SHA256-verifying each; rejects + skips mismatches
  --fetch --base-url URL opt-in network download (https only). Bytes are only written when
                         they match data/manifest.json; otherwise rejected, never faked.

Restore hint: ${RESTORE_HINT}
`;

async function main() {
  const a = parseArgs(process.argv.slice(2));
  if (a.mode === "help") {
    console.log(HELP);
    return;
  }
  const man = loadManifest();
  const files = Object.entries(man.coreset.files);

  if (a.mode === "list") return modeList(man);
  if (a.mode === "prove") return modeProveUnread();
  if (a.mode === "fetch") return modeFetch(a.baseUrl, man);
  if (a.restoreFrom) return modeRestoreFrom(a.restoreFrom, man);

  // default: verify
  const res = verifyAll(files);
  if (res.missing.length === 0 && res.mismatch.length === 0) {
    console.log(
      `[fetch_coreset] OK: ${res.total}/${res.total} coreset files present and SHA256-match data/manifest.json (${human(res.bytes)})`
    );
    return;
  }
  reportIncomplete(res, files);
  process.exit(1);
}

main().catch((e) => {
  console.error(`\n[fetch_coreset] FATAL: ${e && e.stack ? e.stack : e}\n`);
  process.exit(1);
});
